services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: portal_app
    container_name: portal_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./portal:/var/www/html:delegated
    # env_file:
    #   - ./.env
    networks:
      - portal_network

  webserver:
    image: nginx:alpine
    container_name: portal_nginx
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./portal:/var/www/html:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - portal_network

networks:
  portal_network:
    driver: bridge